# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: riscv32-llvm-centos7

on: 
  workflow_dispatch:
  schedule:
    - cron: '42 1 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PKGVERS: riscv32-snitch-llvm-centos7-${{ github.run_number }}
      BUGURL: https://github.com/pulp-platform/snitch-llvm/issues
      BUILDNO: ${{ github.run_number }}
      SSH_PRIVATE_KEY: ${{secrets.SOURCEFORGE_SSH_PRIVATE_KEY}}
      SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      SOURCEFORGE_KEY: ${{ github.workspace }}/../private.key
    steps:
      ########################################
      ## Checkout
      ########################################
      
      ## This
      -
        name: Checkout
        uses: actions/checkout@v2
      
      ## LLVM
      -
        name: Checkout LLVM
        uses: actions/checkout@v2
        with:
          repository: pulp-platform/snitch-llvm
          ref: snitch
          path: llvm-project
      
      ## NEWLIB
      -
        name: Checkout newlib
        run: |
          git clone --depth 1 -b newlib-3.3.0 https://sourceware.org/git/newlib-cygwin.git newlib
      
      ########################################
      ## Build docker container
      ########################################
      -
        name: Prepare Docker
        uses: docker/build-push-action@v2
        with:
          push: false
          file: docker/linux-centos7.Dockerfile
          tags: linux-centos7:latest
      
      ########################################
      ## Build Info
      ########################################
      -
        name: Build Info
        run: |
         docker run -v $PWD:/home/builder -w/home/builder linux-centos7:latest ./builder-info.sh
         cat build-info.txt
      
      ########################################
      ## Build
      ########################################
      -
        name: Build
        run: |
          docker run -v $PWD:/home/builder -w/home/builder \
            -e BUGURL=${BUGURL} \
            -e PKGVERS=${PKGVERS} \
            -e BUILDNO=${BUILDNO} \
            linux-centos7:latest \
            ./stages/build-riscv32-llvm.sh

      ########################################
      ## Package
      ########################################
      -
        name: Package
        run: |
          tar -czf ${PKGVERS}.tar.gz --transform s/^install/${PKGVERS}/ install

      ########################################
      ## Upload
      ########################################
      -
        name: Upload Build Info
        uses: actions/upload-artifact@v2
        with:
          name: Build Info
          path: |
            build-info.txt
      -
        name: Upload Toolchain
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PKGVERS }}
          path: ${{ env.PKGVERS }}.tar.gz

      ########################################
      ## Test
      ########################################
      - 
        name: Test
        run: |
          docker run -v $PWD:/home/builder -w/home/builder \
            -e BUGURL=${BUGURL} \
            -e PKGVERS=${PKGVERS} \
            linux-centos7:latest \
            ./stages/test-llvm.sh
      -
        name: Upload Test Info
        uses: actions/upload-artifact@v2
        with:
          name: Test Info
          path: llvm-tests.log
      - 
        name: Test Snitch
        run: |
          docker run -v $PWD:/home/builder -w/home/builder \
            linux-centos7:latest ./stages/test-snitch-llvm.sh
      -
        name: Upload Snitch Test Info
        uses: actions/upload-artifact@v2
        with:
          name: Snitch Test Info
          path: snitch-tests.log

      ########################################
      ## Deploy
      ########################################
      -
        name: deploy-prepare
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_PRIVATE_KEY}" > ${SOURCEFORGE_KEY}
          sudo chmod 600 ${SOURCEFORGE_KEY}
          echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
      -
        name: deploy-sourceforge
        run: |
          dstname=`echo ${PKGVERS} | rev | cut -d'-' -f 2- | rev`
          scp -i ${SOURCEFORGE_KEY} ${PKGVERS}.tar.gz beeble42brox@frs.sourceforge.net:/home/frs/project/snitch-llvm/nightly/${dstname}.tar.gz
