# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: test-riscv32-llvm

on: 
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      ########################################
      ## Checkout
      ########################################
      
      ## This
      -
        name: Checkout
        uses: actions/checkout@v2
            
      ########################################
      ## Fetch docker containers
      ########################################
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/snitch-llvm.Dockerfile
          tags: |
            snitch-llvm:latest
          push: false

      ########################################
      ## Build Tests
      ########################################
      -
        name: Build Tests
        run: |
         docker run -u root -v $PWD:/src snitch-llvm:latest \
          make -C /src/test/snitch
      -
        name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Build Info
          path: |
            test/snitch/bin
            test/snitch/dump
      
      ########################################
      ## Run Tests
      ########################################
      -
        name: Build Tests
        run: |
         docker run -v $PWD:/src ghcr.io/pulp-platform/snitch:latest \
          make -C /src/test/snitch SHELL=/bin/bash test
      -
        name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Info
          path: |
            test/snitch/log
